# CHAPTER: Matrices (chapter 5)
## Code

In [2]:
# load package
using LinearAlgebra
using ToeplitzMatrices

**Code block 5.1**

In [10]:
A = randn(2, 5)
At1 = A'
At2 = transpose(A)

5×2 transpose(::Matrix{Float64}) with eltype Float64:
  0.420002   0.151817
  0.230691  -1.75383
 -0.610993  -1.69609
 -0.131093  -0.114284
  0.231708  -0.58367

**Code block 5.3**

In [2]:
IM = Matrix(1.0I, 4, 4)
O = ones(4, 4)
Z = zeros(4, 4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

**Code block 5.5**

In [3]:
D = diagm([1, 2, 3, 4, 5])  # diagonal matrix
R = randn(3, 4)
d = diag(R)  # diagonal elements

3-element Vector{Float64}:
 -0.7132279699875074
 -1.1232084349203073
  0.7256254756667967

**Code block 5.7**

In [4]:
A = randn(3, 5)
B = randn(3, 4)
AB = [A B]

3×9 Matrix{Float64}:
  0.0169771   1.36832   1.79203   …   1.45842    0.530294   0.199398
 -0.22109     1.83895   0.189566     -0.0818368  0.347221   1.7454
 -0.016619   -0.954159  0.409262     -1.88682    1.64139   -0.258708

**Code block 5.9**

In [2]:
A = randn(5, 5)
L = tril(A)  # extract the lower triangle
U = triu(A)  # extract the upper triangle

5×5 Matrix{Float64}:
 0.697895   0.967211   0.765131   1.02681    0.014257
 0.0       -0.191803  -0.12209   -1.0753    -0.809057
 0.0        0.0        0.881593   0.530872  -0.95761
 0.0        0.0        0.0       -0.309596  -0.290655
 0.0        0.0        0.0        0.0        2.05462

**Code block 5.11**

In [4]:
t = [1, 2, 3, 4]
T = Toeplitz(t, t)
H = Hankel(t, t[[end, 1:end-1...]])

4×4 Hankel{Int64}:
 1  2  3  4
 2  3  4  1
 3  4  1  2
 4  1  2  3

**Code block 5.13**

In [3]:
l = .01
I4 = Matrix(1.0I, 4, 4)
A = randn(4, 4)
As = A + l*I

4×4 Matrix{Float64}:
  0.660873   0.380825  -0.0930846   0.72783
 -0.466049  -0.841476  -1.16212     0.661831
  1.6214     0.308522  -0.213277   -0.865706
 -0.409756  -0.531536  -0.209967    0.250865

**Code block 5.15**

In [4]:
A = randn(4, 4)
trace = tr(A)

-0.021745589399302767

## Code challenges
**Challenge 1**

In [6]:
A = randn(4, 2)
B = randn(4, 2)
C = zeros(2, 2)
for coli in 1:2
    for colj in 1:2
        C[coli, colj] = A[:, coli] ⋅ B[:, colj]
    end
end
C

2×2 Matrix{Float64}:
 1.68321  -0.0347044
 2.64806   3.39694

**Challenge 2**

In [7]:
A = randn(4, 4)
Al = tril(A)
S = Al + Al'
S

4×4 Matrix{Float64}:
 -1.94925   0.517955  0.121361   1.32322
  0.517955  1.55705   0.420426   0.175252
  0.121361  0.420426  2.61702    0.190952
  1.32322   0.175252  0.190952  -1.13721

**Challenge 3**

In [8]:
D = zeros(4, 8)
for d in 1:min(size(D)...)
    D[d, d] = d
end
D

4×8 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  2.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  3.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  4.0  0.0  0.0  0.0  0.0