# CHAPTER: Matrix multiplication (chapter 6)
## Code

In [3]:
using LinearAlgebra

**Code block 6.1**

In [1]:
M1 = randn(4, 3)
M2 = randn(3, 5)
C = M1 * M2

4×5 Matrix{Float64}:
  4.94176   1.56193    0.670368  -2.9203     1.32124
 -2.68984  -0.543677  -0.214893  -0.776975   0.894268
 -5.80958  -0.274144  -3.08362   -1.91829    0.221431
 -5.7825   -0.896751  -2.85228    1.76259   -1.96322

**Code block 6.3**

In [2]:
A = randn(2, 2)
B = randn(2, 2)
C1 = A * B
C2 = B * A
C1 == C2

false

**Code block 6.5**

In [1]:
M1 = randn(4, 3)
M2 = randn(4, 3)
M1 .* M2

4×3 Matrix{Float64}:
 -0.852296    -0.601538  -2.27973
  0.00380943  -0.193563  -0.00723482
  0.379802     0.211138  -0.017746
  0.103327    -1.05925   -0.0447591

**Code block 6.7**

In [2]:
A = [1 2 3; 4 5 6]
A[:]

6-element Vector{Int64}:
 1
 4
 2
 5
 3
 6

**Code block 6.9**

In [4]:
A = randn(4, 3)
B = randn(4, 3)
f = tr(A' * B)

-1.313321775316375

**Code block 6.11**

In [5]:
A = randn(4, 3)
norm(A)

3.413370258348979

## Code challenges
**Challenge 1**

In [7]:
A = randn(2, 4)
B = randn(4, 3)
C1 = zeros(2, 3)
for i in 1:4
    C1 += A[:, [i]] * B[[i], :]
end
C1 - A * B  # show equality

2×3 Matrix{Float64}:
 0.0   2.77556e-17  0.0
 0.0  -1.11022e-16  0.0

**Challenge 2**

In [8]:
D = diagm(1:4)
A = randn(4, 4)
C1 = D .* A
C2 = D * A
[diag(C1) diag(C2)]

4×2 Matrix{Float64}:
 -1.58443  -1.58443
  1.98175   1.98175
  3.72257   3.72257
 -8.61871  -8.61871

**Challenge 3**

In [10]:
A = diagm(rand(3))
C1 = (A' + A) / 2
C2 = A' * A
C1 - sqrt(C2)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

**Challenge 4**

In [12]:
m = 5
A = randn(m, m)
v = randn(m)
LHS = norm(A * v)
RHS = norm(A) * norm(v)
RHS - LHS  # should always be positive

2.826166373308713