# CHAPTER: Matrices (chapter 5)
## Code

In [1]:
# load package
using LinearAlgebra
using ToeplitzMatrices

**Code block 5.1**

In [10]:
A = randn(2, 5)
At1 = A'
At2 = transpose(A)

5×2 transpose(::Matrix{Float64}) with eltype Float64:
  0.420002   0.151817
  0.230691  -1.75383
 -0.610993  -1.69609
 -0.131093  -0.114284
  0.231708  -0.58367

**Code block 5.3**

In [2]:
IM = Matrix(1.0I, 4, 4)
O = ones(4, 4)
Z = zeros(4, 4)

4×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

**Code block 5.5**

In [3]:
D = diagm([1, 2, 3, 4, 5])  # diagonal matrix
R = randn(3, 4)
d = diag(R)  # diagonal elements

3-element Vector{Float64}:
 -0.7132279699875074
 -1.1232084349203073
  0.7256254756667967

**Code block 5.7**

In [4]:
A = randn(3, 5)
B = randn(3, 4)
AB = [A B]

3×9 Matrix{Float64}:
  0.0169771   1.36832   1.79203   …   1.45842    0.530294   0.199398
 -0.22109     1.83895   0.189566     -0.0818368  0.347221   1.7454
 -0.016619   -0.954159  0.409262     -1.88682    1.64139   -0.258708

**Code block 5.9**

In [2]:
A = randn(5, 5)
L = tril(A)  # extract the lower triangle
U = triu(A)  # extract the upper triangle

5×5 Matrix{Float64}:
 0.697895   0.967211   0.765131   1.02681    0.014257
 0.0       -0.191803  -0.12209   -1.0753    -0.809057
 0.0        0.0        0.881593   0.530872  -0.95761
 0.0        0.0        0.0       -0.309596  -0.290655
 0.0        0.0        0.0        0.0        2.05462

**Code block 5.11**

In [4]:
t = [1, 2, 3, 4]
T = Toeplitz(t, t)
H = Hankel(t, t[[end, 1:end-1...]])

4×4 Hankel{Int64}:
 1  2  3  4
 2  3  4  1
 3  4  1  2
 4  1  2  3